FROM python:3.7
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*
ADD https://github.com/Moonbase59/loudgain/raw/v0.6.8/bin/loudgain.static /usr/local/bin/loudgain
RUN chmod 755 /usr/local/bin/loudgain
RUN pip install poetry
RUN useradd -ms /bin/bash app
RUN mkdir /app && chown app:app /app
WORKDIR /app
USER app
COPY poetry.lock pyproject.toml /app/
RUN mkdir /app/djoek && touch /app/djoek/__init__.py
RUN poetry install --no-dev
COPY migrate.py /app
COPY djoek /app/djoek/
CMD poetry run python migrate.py && \
	poetry run uvicorn --host 0.0.0.0 --log-level warning djoek:app
