version: "3.5"
services:
  mpd:
    image: vimagick/mpd:latest
    volumes:
      - ./conf/mpd.conf:/etc/mpd.conf
      - ./data/mpd:/mpd
      - ./data/music:/music
    restart: always

  front:
    build:
      context: .
      dockerfile: Dockerfile-front
    image: djoek-front:latest

  db:
    image: postgres:11
    volumes:
      - ./conf/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./data/db:/var/lib/postgresql/data
    environment:
      - APP_PASSWORD=${DB_APP_PASSWORD}

  djoek:
    build:
      context: .
      dockerfile: Dockerfile-djoek
    image: djoek:latest
    environment:
      - DJOEK_MPD_HOST=mpd
      - DJOEK_DB_URI=postgres://app:${DB_APP_PASSWORD}@db/app
      - DJOEK_MUSIC_DIR=/music
      - DJOEK_AUTH0_DOMAIN=${DJOEK_AUTH0_DOMAIN}
      - DJOEK_AUTH0_AUDIENCE=${DJOEK_AUTH0_AUDIENCE}
      - DJOEK_AUTH0_PARTIES=${DJOEK_AUTH0_PARTIES}
      - DJOEK_GOOGLE_API_KEY=${DJOEK_GOOGLE_API_KEY}
      - DJOEK_SOUNDCLOUD_CLIENT_ID=${DJOEK_SOUNDCLOUD_CLIENT_ID}
    volumes:
      - ./data/music:/music
