FROM node:lts
COPY booth /app/booth
WORKDIR /app/booth
RUN yarn install && yarn build

FROM nginx:latest
COPY conf/default.conf /etc/nginx/conf.d/default.conf
COPY player /player/
COPY --from=0 /app/booth/dist/ /booth/

