FROM node:lts
COPY booth/package.json booth/yarn.lock /app/booth/
WORKDIR /app/booth
RUN yarn install
COPY booth /app/booth
RUN yarn build

FROM nginx:latest
COPY conf/default.conf /etc/nginx/conf.d/default.conf
COPY player /player/
COPY --from=0 /app/booth/dist/ /booth/

