FROM python:3.8
RUN pip install poetry
RUN useradd -ms /bin/bash app
RUN mkdir /app && chown app:app /app
WORKDIR /app
USER app
ADD poetry.lock pyproject.toml /app/
ADD djoek /app/djoek/
RUN poetry install
CMD poetry run uvicorn --host 0.0.0.0 djoek:app
